### ISSUE TITLE
where is the OSCControlFramework prefab ?

### ISSUE THREAD

**Issue by loisdroug27** [benkuper/Unity-OSCControlFramework#2]
Hi, i would like to use your work but i cant find the OSCControlFramework prefab in the folder. Can you give me some advice to use it because i'm a little bit lost actually i think some of the files are missing. Maybe it's possible to make a asset package to avoid missing files. Thanks.

**Comment by alexbourgeois** [comment]
Hi ! The readme is completely out of date on this repository, you can use https://github.com/theoriz/genui instead. It contains both UI and OSC support. Thank you for your feedback :)

**Comment by loisdroug27** [comment]
Merci beaucoup je vais essayer ça de suite.
